### ISSUE TITLE
Add a combined Docker image 

### ISSUE THREAD

**Issue by auguwu** [auguwu/Arisu#271]
This issue is just a reminder to add a combined image (`arisuland/arisu` is basically the frontend, maybe it could be a combined of Tsubaki and Fubuki (probably new frontend code-name?))

This isn't really the top of my priority to do but, it's just a reminder.

## Task-List
- [ ] Rename everything from the frontend to Fubuki (possible new code-name?)
- [ ] Add a new image: **`arisuland/fubuki`** which will run the frontend server
- [ ] Implement **`arisuland/arisu`** as a combined instance of the two.
