### ISSUE TITLE
[Feature] Transfership

### ISSUE THREAD

**Issue by auguwu** [auguwu/Arisu#93]
This feature will implement transferships between users **OR** organizations.

If the user trying to transfer owns the organization, it will just go in the organization as the owner automatically. If not, the other user must accept a "invitation" to retrieve ownership of the project.

## Roadmap
- [ ] **Implement email microservice**
- [ ] **Email configuration + validation**
- [ ] **Implement invites for private projects**
- [ ] **Implement invites for transferships**

**Comment by auguwu** [comment]
Not on MVP
